### ISSUE TITLE
Failing Build with Cordova 3.4

### ISSUE THREAD

**Issue by hiniesta** [imhotep/MapKit#34]
I have follow the steps on #18. I have install API19 and all extras, included Google Play Services. When I try to run it for android, I get this issue:

-pre-compile:
[echo] Set jars path to: C:\cordova\prueba\platforms\android\CordovaLib\ant-build\classes.jar;C:\adt-bundle\sdk\extras\google\google_play_services\libproject\google-play-services_lib\ant-build\classes.jar;C:\adt-bundle\sdk\extras\google\google_play_services\libproject\google-play-services_lib\libs\google-play-services.jar

-compile:
[javac] Compiling 6 source files to c:\cordova\prueba\platforms\android\ant-build\classes
[javac] c:\cordova\prueba\platforms\android\src\com\phonegap\plugins\mapkit\MapKit.java:73: error: exception GooglePlayServicesNotAvailableException is never thrown in body of corresponding try statement
[javac] } catch (GooglePlayServicesNotAvailableException e) {
[javac] ^
[javac] 1 error

Any idea? Thanks!
